// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcYDuf2HeWRB7JrHLm86nL-YFt3a87j8M',
    appId: '1:320424597302:web:980fa99bb8df0ebee1c597',
    messagingSenderId: '320424597302',
    projectId: 'vcu-student-app',
    authDomain: 'vcu-student-app.firebaseapp.com',
    storageBucket: 'vcu-student-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg-IEFXk4qRdglefD0Am49HYmB6l22nig',
    appId: '1:320424597302:android:a5349315719303cae1c597',
    messagingSenderId: '320424597302',
    projectId: 'vcu-student-app',
    storageBucket: 'vcu-student-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpsBaMqe4kKQEMB-Khw0SvSu2N0sdvoos',
    appId: '1:320424597302:ios:5683e65dc0e6a4f0e1c597',
    messagingSenderId: '320424597302',
    projectId: 'vcu-student-app',
    storageBucket: 'vcu-student-app.appspot.com',
    iosClientId: '320424597302-7fjrskqr5p2jd78evjbqfohrhv9i8hau.apps.googleusercontent.com',
    iosBundleId: 'com.example.vcuadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpsBaMqe4kKQEMB-Khw0SvSu2N0sdvoos',
    appId: '1:320424597302:ios:5683e65dc0e6a4f0e1c597',
    messagingSenderId: '320424597302',
    projectId: 'vcu-student-app',
    storageBucket: 'vcu-student-app.appspot.com',
    iosClientId: '320424597302-7fjrskqr5p2jd78evjbqfohrhv9i8hau.apps.googleusercontent.com',
    iosBundleId: 'com.example.vcuadmin',
  );
}
